[package]
name = "swf-tree"
version = "0.4.1"
authors = ["Charles Samborski <demurgos@demurgos.net>"]
description = "Abstract Syntax Tree (AST) for SWF files"
documentation = "https://github.com/open-flash/swf-tree"
homepage = "https://github.com/open-flash/swf-tree"
repository = "https://github.com/open-flash/swf-tree"
readme = "./README.md"
keywords = ["ast", "swf"]
license = "AGPL-3.0-or-later"
edition = "2018"

[badges]
travis-ci = { repository = "open-flash/swf-tree", branch = "master" }

[lib]
name = "swf_tree"
path = "src/lib.rs"

[[bin]]
name = "swf-tree"
path = "src/main.rs"

[dependencies]
hex = "^0.3.2"
serde = { version = "^1.0.89", features = ["derive"] }
serde_json = "^1.0.39"
swf-fixed = "^0.1.3"

[dev-dependencies]
test-generator = "^0.2.2"
