[package]
name = "swf-tree-bin"
version = "0.5.0"
authors = ["Charles Samborski <demurgos@demurgos.net>"]
description = "Abstract Syntax Tree (AST) for SWF files"
documentation = "https://github.com/open-flash/swf-tree"
homepage = "https://github.com/open-flash/swf-tree"
repository = "https://github.com/open-flash/swf-tree"
readme = "./README.md"
keywords = ["ast", "swf"]
license = "AGPL-3.0-or-later"
edition = "2018"

[badges]
travis-ci = { repository = "open-flash/swf-tree", branch = "master" }

[[bin]]
name = "swf-tree"
path = "src/main.rs"

[dependencies]
serde_json = "^1.0.39"
swf-tree = { path = "../" }
